paths:
  result_path: '../data/results/graph_models/MT_EGBF_sm_vis.pkl'
  dataset_path: '../data/graphs/'
  save_path: '../data/models/MT_EGBF_sm_vis.torch'

dataset:
  n_molecule_level: 1
  n_reaction_level: 1
  max_num_atoms: 50
  self_bond: True
  same_bond: False
  feature_idxs:  [0, 1 , 2, 3, 4, 5, 6, 7, 8, 9, 10]
  feature_sizes: [9, 16, 8, 6, 3, 3, 8, 6, 3, 12, 13]
  target_center: True
  target_main_product: True

model:
  n_hidden: 32
  num_conv_layers: 4
  num_fcn_layers: 1
  num_trans_layers: 0
  num_attention_heads: 2
  num_model_heads: 2
  feature_embed_size: 4


train:
  batch_size: 128
  lr: 0.001
  n_epoches: 5
  exp_step_size: 10000
  eval_names: ['Main product mapping', 'Center of reaction']
